name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v4
      - name: Authenticate in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Creating docker image and pushing
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fake-shop:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fake-shop:v${{ github.run_number }}
        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Authenticate in AWS
        run: echo "Executing the AWS configure command"
      - name: Configuring kubectl
        run: echo "Executing the AWS eks udpate-kubeconfig command"
      - name: Apply manifests to Kubernetes
        run: echo "Executing the Apply kubectl command"
